In [1]:
import pandas as pd
df = pd.read_excel("Online Retail.xlsx")

In [2]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

# checking null values

In [3]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

# removing null values

In [4]:
df = df.dropna(subset=['CustomerID'])

In [5]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

# remove navigation / zero quntity (0)

In [6]:
df = df[df['Quantity']>0] ### filtering

In [7]:
print(df.shape)### validation

(397924, 8)

In [8]:
df['Quantity'].min() ### checking

np.int64(1)

In [9]:
df[df['Quantity'] <= 0] ### varification

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [10]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

# checking

In [11]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [12]:
df['Quantity'].min()

np.int64(1)

In [13]:
df['UnitPrice'].min()

np.float64(0.0)

In [14]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [15]:
import pandas as pd

snapshot_date = df['InvoiceDate'].max() + pd.Timedelta(days=1)

In [16]:
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

In [17]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [18]:
rfm = df.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (snapshot_date - x.max()).days,
    'InvoiceNo': 'nunique',
    'TotalPrice': 'sum'
})

In [19]:
rfm.rename(columns={
    'InvoiceDate': 'Recency',
    'InvoiceNo': 'Frequency',
    'TotalPrice': 'Monetary'
}, inplace=True)

In [20]:
rfm.head()

            Recency  Frequency  Monetary
CustomerID
12346.0         326          1  77183.60
12347.0           2          7   4310.00
12348.0          75          4   1797.24
12349.0          19          1   1757.55
12350.0         310          1    334.40

### scoring

In [21]:
rfm['R_score'] = pd.qcut(rfm['Recency'], 4, labels=[4,3,2,1])

In [22]:
rfm['F_score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 4, labels=[1,2,3,4])

In [23]:
rfm['M_score'] = pd.qcut(rfm['Monetary'], 4, labels=[1,2,3,4])

In [24]:
rfm['RFM_score'] = rfm['R_score'].astype(str) + rfm['F_score'].astype(str) + rfm['M_score'].astype(str)

In [25]:
rfm.head()

            Recency  Frequency  Monetary R_score F_score M_score RFM_score
CustomerID
12346.0         326          1  77183.60       1       1       4       114
12347.0           2          7   4310.00       4       4       4       444
12348.0          75          4   1797.24       2       3       4       234
12349.0          19          1   1757.55       3       1       4       314
12350.0         310          1    334.40       1       1       2       112

### CUSTOMER SEGMENTATION

In [26]:
def segment_customer(row):
    if row['RFM_score'] == '444':
        return 'VIP'
    elif row['F_score'] >= 3:
        return 'Loyal'
    elif row['R_score'] <= 2:
        return 'At Risk'
    else:
        return 'Regular'

In [27]:
rfm['Segment'] = rfm.apply(segment_customer, axis=1)

In [28]:
rfm.head()

,Recency,Frequency,Monetary,R_score,F_score,M_score,RFM_score,Segment
CustomerID,,,,,,,,
12346.0,326,1,77183.60,1,1,4,114,At Risk
12347.0,2,7,4310.00,4,4,4,444,VIP
12348.0,75,4,1797.24,2,3,4,234,Loyal
12349.0,19,1,1757.55,3,1,4,314,Regular
12350.0,310,1,334.40,1,1,2,112,At Risk

In [29]:
rfm['Segment'].value_counts()

Segment
Loyal      1680
At Risk    1504
Regular     666
VIP         489
Name: count, dtype: int64

In [30]:
rfm.to_csv("rfm_output.csv")

In [31]:
rfm.to_csv("rfm_output.csv", index=False)

In [32]:
import os
print(os.getcwd())

C:\Users\lucky\Desktop\RFM.CSV

In [33]:
rfm.to_csv("rfm_output.csv", index=False)

In [34]:
rfm = rfm.reset_index()

In [35]:
rfm.to_csv("rfm_output.csv", index=False)